server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://uname:pwd@loki.domain.com/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 168h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
  - job_name: your-job-name
    static_configs:
      - targets:
        - localhost
        labels:
          job: your-job-name
          host: your.host.name
          __path__: /var/log/some-log-dir/*log